ccats/config/routes.rb
Rails.application.routes.draw do
  resources :reports

  resources :transmissions

  resources :colors

  resources :chasses

  resources :engines

  resources :years

  resources :models

  resources :makes

  resources :emp_jobs

  resources :line_items

  resources :vehicles

  resources :jobs

  resources :appointments

  resources :invoices

  resources :services

  resources :employees

  resources :customers

  resources :surplus_products

  get "/update_price" => "services#update_price"

end

ccats/app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :job


  validates_uniqueness_of :date, scope: [], :message=>"This time is already taken. Please select another time."

end

ccats/app/models/chassis.rb
class Chassis < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/color.rb
class Color < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :invoices
  has_many :vehicles


  def show_full_name
    "#{fname} #{lname}"
  end

end

ccats/app/models/emp_job.rb
class EmpJob < ActiveRecord::Base

  # belongs_to :employee
  # belongs_to :job
end

ccats/app/models/employee.rb
class Employee < ActiveRecord::Base

  # has_many :emp_jobs
  # has_many :jobs, through: :emp_jobs

  has_many :jobs
  has_many :line_items


  def show_full_name
    "#{fname} #{lname}"
  end


  def show_active
    if status?
      "Active"
    else
      "Inactive"
    end
  end
end

ccats/app/models/engine.rb
class Engine < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/invoice.rb
class Invoice < ActiveRecord::Base

  has_many :jobs

  belongs_to :customer


  def show_paid
    if paid?
      "Paid"
    else
      "Due"
    end
  end


end

ccats/app/models/job.rb
class Job < ActiveRecord::Base

  has_many :appointments
  has_many :line_items, dependent: :destroy
  has_many :surplus_products
  # has_many :emp_jobs
  # has_many :employees, through: :emp_jobs

  belongs_to :employee
  belongs_to :vehicle
  belongs_to :invoice, dependent: :destroy


  before_create :auto_create_invoice
  after_update :update_invoice_subtotal


  #returns custom string instead of default boolean status
  def show_complete
    if complete?
      "Finished"
    else
      "In Progress"
    end
  end

  #when a job is marked complete, update invoice subtotal
  def update_invoice_subtotal
    if self.complete?
      Invoice.update(self.invoice_id, :subtotal => self.amount)

      newTax = self.amount * 0.0625

      Invoice.update(self.invoice_id, :tax => newTax)

      newTotal = self.amount + newTax

      Invoice.update(self.invoice_id, :total => newTotal)
    end
  end

  def auto_create_invoice
    if self.invoice_id.nil?
      self.invoice = Invoice.create(customer_id: self.vehicle.customer_id)
    end
  end

end

ccats/app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :job
  belongs_to :service
  belongs_to :employee

  after_save :update_job_amount
  after_save :update_job_status
  after_update :update_job_amount_subtract





  #returns custom string instead of default boolean status
  def show_complete
    if complete?
      "Complete"
    else
      "In Progress"
    end
  end



  #update the Job amount when it's corresponding line item is marked complete
  def update_job_amount

    if self.complete?

      #capture the price of this line item
      x = self.charge
      #find and store corresponding Job
      j = Job.find(self.job_id)

      new_amount = j.amount + x

      #update its amount with the addition of this line items amount
      Job.update(self.job_id, :amount => new_amount)


    end
  end



  #update the Job amount when it's corresponding line item is marked complete
  def update_job_amount_subtract

    if self.complete == false

      #capture the price of this line item
      x = self.charge
      #find and store corresponding Job
      j = Job.find(self.job_id)

      new_amount = j.amount - x

      #update its amount with the addition of this line items amount
      Job.update(self.job_id, :amount => new_amount)

    end
  end



  def update_job_status
    x = true
    j = Job.find(self.job_id)

    j.line_items.each do |line|
      if line.complete?
      else
        x = false
      end

      j.complete = x
      j.save
    end



  end



end

ccats/app/models/make.rb
class Make < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/model.rb
class Model < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/report.rb
class Report < ActiveRecord::Base
end

ccats/app/models/service.rb
class Service < ActiveRecord::Base

  has_many :line_items

end

ccats/app/models/transmission.rb
class Transmission < ActiveRecord::Base
end

ccats/app/models/vehicle.rb
class Vehicle < ActiveRecord::Base

  has_many :jobs

  belongs_to :customer
  belongs_to :make
  belongs_to :model
  belongs_to :year
  belongs_to :color
  belongs_to :engine
  belongs_to :transmission
  belongs_to :chassis


  def show_veh_info
    "#{self.customer.show_full_name}  - #{self.year.mod_year} #{self.make.name} #{self.model.name} #{self.color.name}"
  end

end

ccats/app/models/year.rb
class Year < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json

  def show
    @job= Job.find(params[:id])
    respond_to do |format|
      format.html
      format.pdf do
        pdf = JobPdf.new(@job, view_context)
        send_data pdf.render, filename:
           "job#{@job.created_at.strftime("%d/%m/%Y")}.pdf",
           type: "application/pdf"
      end
    end
  end






  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:vehicle_id, :employee_id, :invoice_id, :amount, :complete, :comments)
    end
end

ccats/app/helpers/colors_helper.rb
module ColorsHelper
end

ccats/app/helpers/jobs_helper.rb
module JobsHelper
end

ccats/app/helpers/makes_helper.rb
module MakesHelper
end

ccats/app/helpers/models_helper.rb
module ModelsHelper




end

ccats/app/helpers/years_helper.rb
module YearsHelper
end

ccats/app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vehicle_id %><br>
    <%= f.collection_select :vehicle_id, Vehicle.all, :id, :show_veh_info, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :employee_id %><br>
    <%= f.collection_select :employee_id, Employee.all, :id, :show_full_name, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :invoice_id %><br>
    <%= f.number_field :invoice_id %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :complete, "Job Complete" %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="field">
    <%= f.label :comments %><br>
    <%= f.text_area :comments %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ccats/app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form' %>


<div>
  <%= button_to "Show Job", @job, :class => "button", :method => :get  %>
</div>
<br>
<div>
  <%= button_to "Back to Jobs", jobs_path, :class => "button", :method => :get  %>
</div>

ccats/app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>
<div>
  <%= button_to "Create New Job", new_job_path, :class => "button", :method => :get  %>
</div>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Job</th>
      <th>Vehicle</th>
      <th>Employee</th>
      <th>Invoice</th>
      <th>Amount</th>
      <th>Job Status</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= job.id %></td>
        <td><%= job.vehicle.show_veh_info %></td>
        <td><%= job.employee.show_full_name %></td>
        <td><%= job.invoice_id %></td>
        <td><%= number_to_currency(job.amount) %></td>
        <td><%= job.show_complete %></td>
        <td><%= job.comments %></td>
        <td class="btn btn-success"><%= link_to 'Show', job %></td>
        <td class="btn btn-warning"><%= link_to 'Edit', edit_job_path(job) %></td>
        <td class="btn btn-danger"><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <%= button_to "Create New Job", new_job_path, :class => "button", :method => :get  %>
</div>

ccats/app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= render 'form' %>

<br>
<div>
  <%= button_to "Back to Jobs", jobs_path, :class => "button", :method => :get  %>
</div>

ccats/app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vehicle:</strong>
  <%= @job.vehicle.show_veh_info %>
</p>

<p>
  <strong>Employee:</strong>
  <%= @job.employee.show_full_name %>
</p>

<p>
  <strong>Invoice:</strong>
  <%= @job.invoice_id %>
</p>

<table class="table table-striped table-hover">
  <thead>
  <tr>
    <th>Service Rendered</th>
    <th>Employee Assigned</th>
    <th>Labor hrs</th>
    <th>Charge</th>
    <th>Job Status</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @job.line_items.each do |j| %>
      <tr>
        <td><%= j.service.desc %></td>
        <td><%= j.employee.show_full_name %></td>
        <td><%= j.labor_hrs %></td>
        <td><%= number_to_currency(j.charge) %></td>
        <td><%= j.show_complete %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<p>
  <strong>Amount:</strong>
  <%= number_to_currency(@job.amount) %>
</p>

<p>
  <strong>Complete:</strong>
  <%= @job.show_complete %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @job.comments %>
</p>


<div>
  <%= button_to "Edit Job",  edit_job_path(@job), :class => "button", :method => :get  %>
</div>
<br>
<div>
  <%= button_to "Back to Jobs", jobs_path, :class => "button", :method => :get  %>
</div>
<br>
<div>
  <button type="button" class="btn btn-default"><%= link_to "Create Line Item Report", job_path(@job, :format => 'pdf') %></button>
</div>