ccats/config/routes.rb
Rails.application.routes.draw do
  resources :reports

  resources :transmissions

  resources :colors

  resources :chasses

  resources :engines

  resources :years

  resources :models

  resources :makes

  resources :emp_jobs

  resources :line_items

  resources :vehicles

  resources :jobs

  resources :appointments

  resources :invoices

  resources :services

  resources :employees

  resources :customers

  resources :surplus_products

  get "/update_price" => "services#update_price"

end

ccats/app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :job


  validates_uniqueness_of :date, scope: [], :message=>"This time is already taken. Please select another time."

end

ccats/app/models/chassis.rb
class Chassis < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/color.rb
class Color < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :invoices
  has_many :vehicles


  def show_full_name
    "#{fname} #{lname}"
  end

end

ccats/app/models/emp_job.rb
class EmpJob < ActiveRecord::Base

  # belongs_to :employee
  # belongs_to :job
end

ccats/app/models/employee.rb
class Employee < ActiveRecord::Base

  # has_many :emp_jobs
  # has_many :jobs, through: :emp_jobs

  has_many :jobs
  has_many :line_items


  def show_full_name
    "#{fname} #{lname}"
  end


  def show_active
    if status?
      "Active"
    else
      "Inactive"
    end
  end
end

ccats/app/models/engine.rb
class Engine < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/invoice.rb
class Invoice < ActiveRecord::Base

  has_many :jobs

  belongs_to :customer


  def show_paid
    if paid?
      "Paid"
    else
      "Due"
    end
  end


end

ccats/app/models/job.rb
class Job < ActiveRecord::Base

  has_many :appointments
  has_many :line_items, dependent: :destroy
  has_many :surplus_products
  # has_many :emp_jobs
  # has_many :employees, through: :emp_jobs

  belongs_to :employee
  belongs_to :vehicle
  belongs_to :invoice, dependent: :destroy


  before_create :auto_create_invoice
  after_update :update_invoice_subtotal


  #returns custom string instead of default boolean status
  def show_complete
    if complete?
      "Finished"
    else
      "In Progress"
    end
  end

  #when a job is marked complete, update invoice subtotal
  def update_invoice_subtotal
    if self.complete?
      Invoice.update(self.invoice_id, :subtotal => self.amount)

      newTax = self.amount * 0.0625

      Invoice.update(self.invoice_id, :tax => newTax)

      newTotal = self.amount + newTax

      Invoice.update(self.invoice_id, :total => newTotal)
    end
  end

  def auto_create_invoice
    if self.invoice_id.nil?
      self.invoice = Invoice.create(customer_id: self.vehicle.customer_id)
    end
  end

end

ccats/app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :job
  belongs_to :service
  belongs_to :employee

  after_save :update_job_amount
  after_save :update_job_status
  after_update :update_job_amount_subtract





  #returns custom string instead of default boolean status
  def show_complete
    if complete?
      "Complete"
    else
      "In Progress"
    end
  end



  #update the Job amount when it's corresponding line item is marked complete
  def update_job_amount

    if self.complete?

      #capture the price of this line item
      x = self.charge
      #find and store corresponding Job
      j = Job.find(self.job_id)

      new_amount = j.amount + x

      #update its amount with the addition of this line items amount
      Job.update(self.job_id, :amount => new_amount)


    end
  end



  #update the Job amount when it's corresponding line item is marked complete
  def update_job_amount_subtract

    if self.complete == false

      #capture the price of this line item
      x = self.charge
      #find and store corresponding Job
      j = Job.find(self.job_id)

      new_amount = j.amount - x

      #update its amount with the addition of this line items amount
      Job.update(self.job_id, :amount => new_amount)

    end
  end



  def update_job_status
    x = true
    j = Job.find(self.job_id)

    j.line_items.each do |line|
      if line.complete?
      else
        x = false
      end

      j.complete = x
      j.save
    end



  end



end

ccats/app/models/make.rb
class Make < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/model.rb
class Model < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/report.rb
class Report < ActiveRecord::Base
end

ccats/app/models/service.rb
class Service < ActiveRecord::Base

  has_many :line_items

end

ccats/app/models/transmission.rb
class Transmission < ActiveRecord::Base
end

ccats/app/models/vehicle.rb
class Vehicle < ActiveRecord::Base

  has_many :jobs

  belongs_to :customer
  belongs_to :make
  belongs_to :model
  belongs_to :year
  belongs_to :color
  belongs_to :engine
  belongs_to :transmission
  belongs_to :chassis


  def show_veh_info
    "#{self.customer.show_full_name}  - #{self.year.mod_year} #{self.make.name} #{self.model.name} #{self.color.name}"
  end

end

ccats/app/models/year.rb
class Year < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)

    respond_to do |format|
      if @line_item.save
        format.html { redirect_to @line_item, notice: 'Line item was successfully created.' }
        format.json { render :show, status: :created, location: @line_item }
      else
        format.html { render :new }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        format.html { redirect_to @line_item, notice: 'Line item was successfully updated.' }
        format.json { render :show, status: :ok, location: @line_item }
      else
        format.html { render :edit }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    @line_item.destroy
    respond_to do |format|
      format.html { redirect_to line_items_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item = LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:job_id, :employee_id, :service_id, :labor_hrs, :charge, :complete)
    end
end

ccats/app/helpers/colors_helper.rb
module ColorsHelper
end

ccats/app/helpers/jobs_helper.rb
module JobsHelper
end

ccats/app/helpers/line_items_helper.rb
module LineItemsHelper
end

ccats/app/helpers/makes_helper.rb
module MakesHelper
end

ccats/app/helpers/years_helper.rb
module YearsHelper
end

ccats/app/views/line_items/_form.html.erb
<%= form_for(@line_item) do |f| %>

    <script>
        function update_price() {

            var newPrice = document.getElementById("line_item_service_id").value;
            console.log(newPrice);
            jQuery.ajax({
                url: "/update_price",
                type: "GET",
                data: {"service_id" : newPrice},
                dataType: "html",
                success: function(data) {
                    jQuery("#line_item_charge").html(data);
                }
            });
        }</script>


  <% if @line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@line_item.errors.count, "error") %> prohibited this line_item from being saved:</h2>

      <ul>
      <% @line_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :job_id %><br>
    <%= f.collection_select :job_id, Job.all, :id, :id, prompt: true %>
  </div>
  <div class="field">
    <%= f.label :employee_id,"Technician" %><br>
    <%= f.collection_select :employee_id, Employee.all, :id, :show_full_name, prompt: true %>
  </div>
    <div class="field">
      <%= f.label :service_id %><br>
      <%= f.collection_select(:service_id, Service.all, :id, :desc, {prompt: true}, {:onchange => "update_price(this.value)", :onload => "update_price(this.value)"}) %>
    </div>
  <div class="field">
    <%= f.label :labor_hrs %><br>
    <%= f.text_field :labor_hrs %>
  </div>
  <div class="field">
    <%= f.label :charge %><br>
    <%= f.text_field :charge %>
  </div>
  <div class="field">
    <%= f.label :complete, "Line Item Complete" %><br>
    <%= f.check_box :complete %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ccats/app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>


<div>
  <%= button_to "Show Line Items", @ine_item, :class => "button", :method => :get  %>
</div>
<br>
<div>
  <%= button_to "Back to Line Items", line_items_path, :class => "button", :method => :get  %>
</div>

ccats/app/views/line_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Line Items</h1>
<div>
<%= button_to "Create New Line Item", new_line_item_path, :class => "button", :method => :get  %>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Job</th>
      <th>Technician</th>
      <th>Service</th>
      <th>Labor hrs</th>
      <th>Charge</th>
      <th>Line Item Complete</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
        <td><%= line_item.job_id %></td>
        <td><%= line_item.employee.show_full_name %></td>
        <td><%= line_item.service_id %></td>
        <td><%= line_item.labor_hrs %></td>
        <td><%= number_to_currency(line_item.charge) %></td>
        <td><%= line_item.show_complete %></td>
        <td class="btn btn-success"><%= link_to 'Show', line_item %></td>
        <td class="btn btn-warning"><%= link_to 'Edit', edit_line_item_path(line_item) %></td>
        <td class="btn btn-danger"><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <%= button_to "Create New Line Item", new_line_item_path, :class => "button", :method => :get  %>
</div>

ccats/app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

<br>
<div>
  <%= button_to "Back to Line Items", line_items_path, :class => "button", :method => :get  %>
</div>

ccats/app/views/line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Job:</strong>
  <%= @line_item.job_id %>
</p>

<p>
  <strong>Technician:</strong>
  <%= @line_item.employee.show_full_name %>
</p>

<p>
  <strong>Service:</strong>
  <%= @line_item.service.desc %>
</p>

<p>
  <strong>Labor hours:</strong>
  <%= @line_item.labor_hrs %>
</p>

<p>
  <strong>Charge:</strong>
  <%= number_to_currency(@line_item.charge) %>
</p>

<p>
  <strong>Line Item Complete:</strong>
  <%= @line_item.show_complete %>
</p>

<div>
  <%= button_to "Edit Line Items", edit_line_item_path, :class => "button", :method => :get  %>
</div>
<br>
<div>
  <%= button_to "Back to Line Items", line_items_path, :class => "button", :method => :get  %>
</div>