ccats/config/routes.rb
Rails.application.routes.draw do
  resources :reports

  resources :transmissions

  resources :colors

  resources :chasses

  resources :engines

  resources :years

  resources :models

  resources :makes

  resources :emp_jobs

  resources :line_items

  resources :vehicles

  resources :jobs

  resources :appointments

  resources :invoices

  resources :services

  resources :employees

  resources :customers

  resources :surplus_products

  get "/update_price" => "services#update_price"

end

ccats/app/models/appointment.rb
class Appointment < ActiveRecord::Base

  belongs_to :job


  validates_uniqueness_of :date, scope: [], :message=>"This time is already taken. Please select another time."

end

ccats/app/models/chassis.rb
class Chassis < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/color.rb
class Color < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/customer.rb
class Customer < ActiveRecord::Base

  has_many :invoices
  has_many :vehicles


  def show_full_name
    "#{fname} #{lname}"
  end

end

ccats/app/models/emp_job.rb
class EmpJob < ActiveRecord::Base

  # belongs_to :employee
  # belongs_to :job
end

ccats/app/models/employee.rb
class Employee < ActiveRecord::Base

  # has_many :emp_jobs
  # has_many :jobs, through: :emp_jobs

  has_many :jobs
  has_many :line_items


  def show_full_name
    "#{fname} #{lname}"
  end


  def show_active
    if status?
      "Active"
    else
      "Inactive"
    end
  end
end

ccats/app/models/engine.rb
class Engine < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/invoice.rb
class Invoice < ActiveRecord::Base

  has_many :jobs

  belongs_to :customer


  def show_paid
    if paid?
      "Paid"
    else
      "Due"
    end
  end


end

ccats/app/models/job.rb
class Job < ActiveRecord::Base

  has_many :appointments
  has_many :line_items, dependent: :destroy
  has_many :surplus_products
  # has_many :emp_jobs
  # has_many :employees, through: :emp_jobs

  belongs_to :employee
  belongs_to :vehicle
  belongs_to :invoice, dependent: :destroy


  before_create :auto_create_invoice
  after_update :update_invoice_subtotal


  #returns custom string instead of default boolean status
  def show_complete
    if complete?
      "Finished"
    else
      "In Progress"
    end
  end

  #when a job is marked complete, update invoice subtotal
  def update_invoice_subtotal
    if self.complete?
      Invoice.update(self.invoice_id, :subtotal => self.amount)

      newTax = self.amount * 0.0625

      Invoice.update(self.invoice_id, :tax => newTax)

      newTotal = self.amount + newTax

      Invoice.update(self.invoice_id, :total => newTotal)
    end
  end

  def auto_create_invoice
    if self.invoice_id.nil?
      self.invoice = Invoice.create(customer_id: self.vehicle.customer_id)
    end
  end

end

ccats/app/models/line_item.rb
class LineItem < ActiveRecord::Base

  belongs_to :job
  belongs_to :service
  belongs_to :employee

  after_save :update_job_amount
  after_save :update_job_status
  after_update :update_job_amount_subtract





  #returns custom string instead of default boolean status
  def show_complete
    if complete?
      "Complete"
    else
      "In Progress"
    end
  end



  #update the Job amount when it's corresponding line item is marked complete
  def update_job_amount

    if self.complete?

      #capture the price of this line item
      x = self.charge
      #find and store corresponding Job
      j = Job.find(self.job_id)

      new_amount = j.amount + x

      #update its amount with the addition of this line items amount
      Job.update(self.job_id, :amount => new_amount)


    end
  end



  #update the Job amount when it's corresponding line item is marked complete
  def update_job_amount_subtract

    if self.complete == false

      #capture the price of this line item
      x = self.charge
      #find and store corresponding Job
      j = Job.find(self.job_id)

      new_amount = j.amount - x

      #update its amount with the addition of this line items amount
      Job.update(self.job_id, :amount => new_amount)

    end
  end



  def update_job_status
    x = true
    j = Job.find(self.job_id)

    j.line_items.each do |line|
      if line.complete?
      else
        x = false
      end

      j.complete = x
      j.save
    end



  end



end

ccats/app/models/make.rb
class Make < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/model.rb
class Model < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/models/report.rb
class Report < ActiveRecord::Base
end

ccats/app/models/service.rb
class Service < ActiveRecord::Base

  has_many :line_items

end

ccats/app/models/transmission.rb
class Transmission < ActiveRecord::Base
end

ccats/app/models/vehicle.rb
class Vehicle < ActiveRecord::Base

  has_many :jobs

  belongs_to :customer
  belongs_to :make
  belongs_to :model
  belongs_to :year
  belongs_to :color
  belongs_to :engine
  belongs_to :transmission
  belongs_to :chassis


  def show_veh_info
    "#{self.customer.show_full_name}  - #{self.year.mod_year} #{self.make.name} #{self.model.name} #{self.color.name}"
  end

end

ccats/app/models/year.rb
class Year < ActiveRecord::Base

  has_many :vehicles
end

ccats/app/controllers/chasses_controller.rb
class ChassesController < ApplicationController
  before_action :set_chass, only: [:show, :edit, :update, :destroy]

  # GET /chasses
  # GET /chasses.json
  def index
    @chasses = Chassis.all
  end

  # GET /chasses/1
  # GET /chasses/1.json
  def show
  end

  # GET /chasses/new
  def new
    @chass = Chassis.new
  end

  # GET /chasses/1/edit
  def edit
  end

  # POST /chasses
  # POST /chasses.json
  def create
    @chass = Chassis.new(chass_params)

    respond_to do |format|
      if @chass.save
        format.html { redirect_to @chass, notice: 'Chassis was successfully created.' }
        format.json { render :show, status: :created, location: @chass }
      else
        format.html { render :new }
        format.json { render json: @chass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /chasses/1
  # PATCH/PUT /chasses/1.json
  def update
    respond_to do |format|
      if @chass.update(chass_params)
        format.html { redirect_to @chass, notice: 'Chassis was successfully updated.' }
        format.json { render :show, status: :ok, location: @chass }
      else
        format.html { render :edit }
        format.json { render json: @chass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /chasses/1
  # DELETE /chasses/1.json
  def destroy
    @chass.destroy
    respond_to do |format|
      format.html { redirect_to chasses_url, notice: 'Chassis was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_chass
      @chass = Chassis.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def chass_params
      params.require(:chass).permit(:code)
    end
end

ccats/app/helpers/chasses_helper.rb
module ChassesHelper
end

ccats/app/helpers/jobs_helper.rb
module JobsHelper
end

ccats/app/helpers/makes_helper.rb
module MakesHelper
end

ccats/app/helpers/years_helper.rb
module YearsHelper
end

ccats/app/views/chasses/_form.html.erb
<%= form_for(@chass) do |f| %>
  <% if @chass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chass.errors.count, "error") %> prohibited this chassis from being saved:</h2>

      <ul>
      <% @chass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_field :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ccats/app/views/chasses/edit.html.erb
<h1>Editing Chassis Code</h1>

<%= render 'form' %>

<%= link_to 'Show', @chass %> |
<%= link_to 'Back', chasses_path %>
<div>
  <%= button_to "Show Chassis", @chass, :class => "button", :method => :get  %>
</div>
<br>
<div>
  <%= button_to "Back to Chassis", chass_path, :class => "button", :method => :get  %>
</div>

ccats/app/views/chasses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Chassis Codes</h1>
<div>
  <%= button_to "Create New Chassis Code", new_chass_path, :class => "button", :method => :get  %>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Code</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @chasses.each do |chass| %>
      <tr>
        <td><%= chass.code %></td>
        <td class="btn btn-success"><%= link_to 'Show', chass %></td>
        <td class="btn btn-warning"><%= link_to 'Edit', edit_chass_path(chass) %></td>
        <td class="btn btn-danger"><%= link_to 'Destroy', chass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div>
  <%= button_to "Create New Chassis Code", new_chass_path, :class => "button", :method => :get  %>
</div>

ccats/app/views/chasses/new.html.erb
<h1>New Chassis Code</h1>

<%= render 'form' %>

<div>
  <%= button_to "Back to Chassis", chasses_path, :class => "button", :method => :get  %>
</div>

ccats/app/views/chasses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @chass.code %>
</p>

<div>
  <%= button_to "Edit Chassis Code", edit_chass_path, :class => "button", :method => :get  %>
</div>
<br>
<div>
  <%= button_to "Back to Chassis", chasses_path, :class => "button", :method => :get  %>
</div>